### ISSUE TITLE
PHPcs encoding issue

### ISSUE THREAD

**Issue by tyler36** [JustBlackBird/gulp-phpcs#10]
I'm trying to run gulp-phpcs but have an encoding issue with the output.

I'm running Windows 7 x64 Japanese edition.
I noticed the issue when running through Phpstorm 9's terminal. I tried a different terminal wrapper (ConEmu) but with the same results.

Results show fine if SSH into a Homestead 2 environment (both via PHPstore or via ConEmu).

How can I get it to display correctly in Windows?

![clipboard01](https://cloud.githubusercontent.com/assets/7234392/8716733/f7f06490-2bce-11e5-8108-7e52ef23e43d.jpg)
PS. Screenshot of displayed error - English and Japanese both display fine in the console. PHPcs error does not.

**Comment by JustBlackBird** [comment]
`gulp-phpcs` is just a wrapper around PHPCS utility. So the first thing you should to try is run PHPCS directly via CLI. Is the problem persists?

**Comment by tyler36** [comment]
I tried your suggestion.
```
phpcs ..\..\gulp-tasks
```
results in various 'errors' in several files
```
FILE: I:\Lavarel\testserver\gulp-tasks\gulp-tasks\sassdoc.js
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
  1 | ERROR | [x] End of line character is invalid; expected "\n" but
    |       |     found "\r\n"
  2 | ERROR | [ ] Doc comment short description must start with a
    |       |     capital letter
----------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

however
```
gulp phpcs
```

generates bad output
```
[09:09:39] PHP Code Sniffer found a problem in I:\Lavarel\testserver\gulp-tasks\gulp-tasks\sassdoc.js
Message:
    Error: Command failed: '.' �́A�����R�}���h�܂��͊O���R�}���h�A
�����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF�������Ă��܂����B
[09:09:39] Finished 'phpcs' after 928 ms
```

**Comment by JustBlackBird** [comment]
Well, I cannot reproduce the issue you are talking about. Is the project you're working on an open-source one?

**Comment by tyler36** [comment]
Sorry for the delay. Thanks for taking the time to help me with this.

I have created a bitbucket git repo: git@bitbucket.org:
shendrix_IQ/test-gulp-phpcs.git

This was created with:
1. Install Compose: "composer init"
2. Install gulp-phpcs: "npm install gulp-phpcs --save-dev"
3. Install php_codesniffer: added to composer file

"{
    "require-dev": {
        "squizlabs/php_codesniffer": "2.*"
    }
}"

4. Run composer: "composer update"

5. Install gulp: "npm install gulp"

6. Create gulp file

7. Add dummy test file

8. Run: "gulp"



It's probably something stupid I'm doing wrong, but it's really
annoying me trying to get it working. Any help is greatly appreciated.
Thanks again for your time



On 29 July 2015 at 23:37, Dmitriy Simushev <notifications@github.com> wrote:

> Well, I cannot reproduce the issue you are talking about. Is the project
> you're working on an open-source one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JustBlackBird/gulp-phpcs/issues/10#issuecomment-125971802>
> .
>



-- 
==================================================
株式会社インタークエスト
システム開発部 Shane Hendrix
mailto:s.hendrix@iqnet.co.jp
http://www.iqnet.co.jp/ ←☆日々更新中！☆
--------------------------------------------------
[本社] 〒541-0054
大阪市中央区南本町3-1-12カネセ中央ビル8F
TEL: 06-6120-1320 FAX: 06-6120-1303
[東京支社] 〒153-0063
東京都目黒区目黒1-24-12オリックス目黒ビル2F
TEL: 03-5434-8200 FAX: 03-5434-8201
--------------------------------------------------
■フォーム作成・アンケート・メール配信・ユーザー管理に
簡単・低価格・セキュアな「IQ-FORM」が便利です！
http://iq-form.iqnet.co.jp/

■製品の脆弱性チェックガイドラインを公開しました！
http://www.iqnet.co.jp/products-reservation-engine/security.html
受託開発・製品に関するセキュリティや品質向上に取り組んでいます
==================================================

**Comment by JustBlackBird** [comment]
First of all make sure you've installed gulp itself with `npm install gulp --save-dev` command.

Next, your gulp file is invalid. Here is the correct one:

```js
var gulp = require('gulp');
var phpcs = require('gulp-phpcs');

gulp.task('default', function () {
    return gulp.src(['src/**/*.php'])
        // Validate files using PHP Code Sniffer
        .pipe(phpcs({
            bin: 'vendor/bin/phpcs',
            standard: 'PSR2',
            warningSeverity: 0
        }))
        // Log all problems that was found
        .pipe(phpcs.reporter('log'));
});
```

After all the corrected example works fine for me, so I don't see any problems with `gulp-phpcs`.

**Comment by tyler36** [comment]
Thank you for the advice, unfortunately it is still not working for me
I ran the npm command as you said and replaced my gulp file with the correct one.

I get the following
```
[09:18:45] PHP Code Sniffer found a problem in I:\gulp-phpcs\src\test.php
Message:
    Error: Command failed: 'vendor' �́A�����R�}���h�܂��͊O���R�}���h�A
�����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF�������Ă��܂����B
'''

Thanks for you help. I guess I'll just ran the command manually.

CLOSE: unable to reproduce

**Comment by JustBlackBird** [comment]
One more guess: did not you try to specify full path to composer's executable with windows-style slashes?

**Comment by tyler36** [comment]
OK ... been working on this for a while now.

The following works in Homestead 2, but not Win7
```
        .pipe(phpcs({
            bin: './vendor/bin/phpcs',
```

The following works in Win7, but not Homestead
```
        .pipe(phpcs({
            bin: '.\\vendor\\bin\\phpcs',
```

**Solution 1: **
I first tried a Windows TEST to my gulpfile.js. But it felt a little hack-y and not very dynamic.
```
var isWin = /^win/.test(process.platform);
var phpcsBIN = (isWin) ? '.\\vendor\\bin\\phpcs' : './vendor/bin/phpcs'

gulp.task('default', function () {
    return gulp.src(['src/**/*.php'])
        .pipe(phpcs({
            bin: phpcsBIN,
...
```

**Solution 2:**
I stumbled across the Nodejs PATH functions and tried that which also worked in both
[Link to PATH doc](https://nodejs.org/api/path.html)
```
var path = require('path');

gulp.task('default', function () {
    return gulp.src(['src/**/*.php'])
        .pipe(phpcs({
            bin: path.normalize('./vendor/bin/phpcs'),
...
```

**Solution 3:**
Ultimately, I forked the repo and made a pull request so that this might help others.

**Comment by JustBlackBird** [comment]
It seems that the best option is "solution 2" you've proposed. I've described the reason why we cannot use "solution 3" [here](https://github.com/JustBlackBird/gulp-phpcs/pull/13#issuecomment-128446843).

**Comment by tyler36** [comment]
Thanks for explaining. 

CLOSE:  Resolved
