### ISSUE TITLE
No option for creating reports

### ISSUE THREAD

**Issue by culleningus** [JustBlackBird/gulp-phpcs#11]
It would be great if we could pass through a report option.

https://pear.php.net/manual/en/package.php.php-codesniffer.reporting.php

**Comment by culleningus** [comment]
I've forked and added the options here:

https://github.com/JustBlackBird/gulp-phpcs/pull/12

**Comment by JustBlackBird** [comment]
Actually, File reporter was added in `v1.0.0`, so there is no need for `--report-file` option.
