### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by fntneves** [JustBlackBird/gulp-phpcs#24]
How do I specify .php_cs config file ?

**Comment by JustBlackBird** [comment]
You cannot.

**Comment by JustBlackBird** [comment]
I want to add some more details here.

`gulp-phpcs` is not just a runner for PHPCS CLI util. I tried to encapsulate all PHPCS CLI options, stdin, stdout, errors handling inside the plugin. In this case one can easily use `gulp-phpcs` within _Gulp way_. So there is no need for using PHPCS configs file: all options are stored in your `gulpfile.js` as `gulp-phpcs` plugin's options.
