### ISSUE TITLE
Add the exclude option

### ISSUE THREAD

**Issue by tdmalone** [JustBlackBird/gulp-phpcs#29]
gulp-phpcs currently supports the `sniffs` option, which is equivalent to the phpcs `--sniffs` option.

Could the `exclude` option also be added, equivalent to the phpcs `--exclude` option? The syntax is the same; it just does the opposite and is useful for excluding one or two sniffs from the standards.

**Comment by JustBlackBird** [comment]
Sorry for the late answer, it was busy time :sweat_smile: 

I've checked PHPCS docs about `--exclude` option and I think it's possible to add it to `gulp-phpcs`. The bad news are I need some time to implement it by myself.

**Comment by JustBlackBird** [comment]
Done in v1.2.0
