### ISSUE TITLE
Output file name with errors when using 'fail' reporter

### ISSUE THREAD

**Issue by ukneeq** [JustBlackBird/gulp-phpcs#31]
I noticed that when using the 'fail' reporter and setting failOnFirst to false that it generates the following output when it sees errors:
Message:
    PHP Code Sniffer failed at least at one file.

Have you thought about adding the ability to see all the files that failed? Or even a more verbose output that shows file and the actual errors like on the 'log' reporter but giving the fail return code? This would be useful out when combined with an automated CI pipeline.

**Comment by JustBlackBird** [comment]
Actually the only purpose of `fail` reporter is to break gulp task with error.

I don't think something should be added there. At the same time an extra reporter which just outputs bad files could be useful. It can be used with or without `fail` reporter to provide better flexibility.

**Comment by JustBlackBird** [comment]
After some more thoughts about the problem I've modified Fail reporter to make it output all the bad files with `failOnFirst = false` . The changes was released as v1.4.0.
