### ISSUE TITLE
Implementing autofix

### ISSUE THREAD

**Issue by webcodecs** [JustBlackBird/gulp-phpcs#32]
Hey, i would like to use the "auto fix" within this plugin.
Is this feature on track or something?

**Comment by JustBlackBird** [comment]
There is no such feature at the project's roadmap.

Moreover I'm not sure it can be easily implemented because gulp-phpcs works with files from gulp stream (via stdin, stdout, stderr) and not with files on filesystem. That's why there could be some problems with file contents transformation.

**Comment by JustBlackBird** [comment]
At the moment I don't see any possibility to implement the feature in gulp-phpcs.
