### ISSUE TITLE
Not compatible with phpcs vs 3

### ISSUE THREAD

**Issue by dave-stevens-net** [JustBlackBird/gulp-phpcs#33]
When I use gulp-phpcs with version 3 of phpcs I don't get any output. However, when I add a console.log to line 159 of index.js the following error is repeated over and over again. I'm running this on Windows 10 using Git CMD.

```
ERROR: You must supply at least one file or directory to process.
Usage: phpcs [-nwlsaepqvi] [-d key[=value]] [--cache[=<cacheFile>]] [--no-cache] [--colors] [--no-colors]
```

**Comment by JustBlackBird** [comment]
New version (`gulp-phpcs@2.0.0`) is released. It should be compatible with PHPCS 3.x. If it's not let me know and I'll reopen the issue.
