### ISSUE TITLE
Broken exit codes for PHPCS 3.0

### ISSUE THREAD

**Issue by JustBlackBird** [JustBlackBird/gulp-phpcs#34]
PHPCS 2.x uses only exit code `1` to indicate coding standard violation and some other codes for PHPCS errors. Version 3.0 uses both `1` and `2` for coding standard violations error, so `gulp-phpcs` should be fixed to work with it.

**Comment by jblotus** [comment]
is there a way to fix this so we can use 3.0?

**Comment by JustBlackBird** [comment]
Fixed and released as v2.0.0
